### ISSUE TITLE
Upgrade to scrapy 2.6.0 (#8)

### ISSUE THREAD

**Issue by torbencarstens** [woog-life/scrapers#13]
```
2022-06-10 10:00:07 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'lake_scrapers',
 'NEWSPIDER_MODULE': 'lake_scrapers.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['lake_scrapers.spiders'],
 'USER_AGENT': 'lake_scrapers (admin@woog.life)'}
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 12, in <module>
    process.crawl(WoogSpider)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 205, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 238, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 313, in _create_crawler
    return Crawler(spidercls, self.settings, init_reactor=True)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 82, in __init__
    default.install()
  File "/usr/local/lib/python3.10/site-packages/twisted/internet/epollreactor.py", line 256, in install
    installReactor(p)
  File "/usr/local/lib/python3.10/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed
```

**Comment by torbencarstens** [comment]
Closed by 8f4dada
